### ISSUE TITLE
Improve hsload --link performance

### ISSUE THREAD

**Issue by jreadey** [HDFGroup/nasa_cloud#5]
Use H5Dchunk_iter rather than chunk_info in: https://github.com/HDFGroup/h5pyd/blob/master/h5pyd/_apps/utillib.py.
Testing shows that this can have a speed up of over 500x for datasets with large number of chunks.
Verify the hdf5lib version and fall back to chunk_info if H5Dchunk_iter is not available.

**Comment by mattjala** [comment]
My [initial test](https://github.com/mattjala/h5pyd/commit/58f6808987909be6cc110fb83e22f707809e0910) actually showed a slight slowdown when I tried it on the ATL03 file - 25.3 minutes with `get_chunk_info`, 26.8 minutes with `chunk_iter`.

**Comment by ajelenak** [comment]
Try with the cloud-optimized version of that file.

**Comment by mattjala** [comment]
> Try with the cloud-optimized version of that file.

Are you talking about using a paging strategy with page size 4-8 Mb? The ATL file is using the `H5F_FSPACE_STRATEGY_FSM_AGGR` strategy, and the documentation says the strategy and page size are immutable for an already created file. If there are external tools that can alter this, I'm not aware of them.

**Comment by mattjala** [comment]
Implemented in HDFGroup/h5pyd#148
